version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor:
      name: win/default
    steps:
      - checkout
      - run: echo 'Hello, Windows'
      - run: uname -a
      - run: where docker
      - run:
         command: wmic product get name,version
         shell: cmd.exe
      - run:
         command: choco list --local
         shell: cmd.exe
      - run:
         command: Get-WmiObject -Class Win32_Product | Select-Object -Property Name, Version
         shell: powershell.exe
